# Generated by Django 3.0.4 on 2020-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostSeen',
        ),
    ]
